### ISSUE TITLE
BUG: Отключается бот

### ISSUE THREAD

**Issue by fet1sov** [gramiojs/gramio#2]
# Описание
Вообщем бот почему-то спустя какое-то время падает, не знаю честно говоря с чем может быть связано, пока-что не углублялся в вопрос о том как работает либа.

Проходит определённое время, библиотека перестаёт принимать запросы на команды.
Может быть это как-то связано с телеграмовскими ограничениями?

Собираю всё докере держу в отдельном контейнере.

# Кусочки кода
**_Класс бота bot.ts_**
```ts
class TGBot {
    bot: Bot;
    commands: Command[] = [];

    constructor(private readonly configService: IConfigService) {
        this.bot = new Bot(this.configService.get("TOKEN"))
        .extend(session())
        .extend(i18n<TypedFluentBundle>())
            .onStart(({ info }) => console.log(`✨ Bot ${info.username} was started!`));
    }

    init() {
        this.commands = [new StartCommand(this.bot)];
        for (const command of this.commands) {
            command.handle();
        }
        
        this.bot.start();
    }
}

const bot = new TGBot(new ConfigService());
bot.init();
```

**Comment by kravetsone** [comment]
Привет! В новой версии [@0.0.41](https://github.com/gramiojs/gramio/releases/tag/v0.0.41) добавил обработку ошибок в обработчике long-polling и думаю что это может помочь

Так же теперь можно дебажить API запросы к Telegram если перед запуском установить переменную окружения `DEBUG=gramio*`

**Comment by fet1sov** [comment]
Привет, попробуй проапгрейдить пакет, пасиб большое.
Посмотрю что да как, дам знать)

**Comment by fet1sov** [comment]
Да теперь всё впорядке, пересобрал под новую версию.
Видимо падало из-за обработчика ошибок

Пасиб большое за фикс, буду дальше пользоваться либой.
Классные мидлвары, очень **удобный i18n для локализации самое то :)**
