### ISSUE TITLE
Не работает oneTime с requestContact

### ISSUE THREAD

**Issue by zelenovsky** [gramiojs/gramio#4]
Делаю вот так, но кнопка остается

```js
reply_markup: new Keyboard()
        .requestContact("Поделиться номером")
        .oneTime(),
```

**Comment by kravetsone** [comment]
Привет! Не могу воспроизвести проблему. Проверял на десктопной и Android-версии, и при нажатии на "поделиться номером" кнопки скрываются (но не удаляются), как и должны

**Comment by kravetsone** [comment]
> Делаю вот так, но кнопка остается
> 
> ```js
> reply_markup: new Keyboard()
>         .requestContact("Поделиться номером")
>         .oneTime(),
> ```

Привет! Что в итоге?

**Comment by zelenovsky** [comment]
@kravetsone Привет! решил проблему через отправку следующим сообщением 
```js
reply_markup: new RemoveKeyboard()
```
больше не тестировал

**Comment by kravetsone** [comment]
> @kravetsone Привет! решил проблему через отправку следующим сообщением
> 
> ```js
> reply_markup: new RemoveKeyboard()
> ```
> 
> больше не тестировал

Отлично) Этот вид клавиатуры как раз и удаляет её, а не скрывает. Спасибо за использование GramIO)

**Comment by zelenovsky** [comment]
@kravetsone о то что вы делаете это вообще круто) я подобных библиотек не видел на столько удобных и качественно написанных

**Comment by kravetsone** [comment]
> @kravetsone о то что вы делаете это вообще круто) я подобных библиотек не видел на столько удобных и качественно написанных

Стараюсь) есть ещё много крутых идей, но щас как-то времени нет

**Comment by zelenovsky** [comment]
@kravetsone я кстати воспроизвел баг с клавиатурой) воспроизводится только на десктоп версии на маке. клавиатура исчезает но не удаляется. 

у меня beta версия телеграм установлена (там можно mini apps дебажить)

а вот на ios норм все

**Comment by kravetsone** [comment]
> @kravetsone я кстати воспроизвел баг с клавиатурой) воспроизводится только на десктоп версии на маке. клавиатура исчезает но не удаляется. 
> 
> у меня beta версия телеграм установлена (там можно mini apps дебажить)
> 
> а вот на ios норм все

oneTime клавиатура по идее и должна скрываться, но не удаляться

> Optional. Requests clients to hide the keyboard as soon as it's been used. The keyboard will still be available, but clients will automatically display the usual letter-keyboard in the chat - the user can press a special button in the input field to see the custom keyboard again. Defaults to false.

**Comment by zelenovsky** [comment]
@kravetsone тогда RemoveKeyboard по разному отрабатывает)

**Comment by kravetsone** [comment]
> @kravetsone тогда RemoveKeyboard по разному отрабатывает) или просто баг в бете

Возможно) телеграм славится различным поведением клиентов
