### ISSUE TITLE
inlineQuery not working at all

### ISSUE THREAD

**Issue by DeluxeOwl** [gramiojs/gramio#6]
Am I not using `inlineQuery` properly? This doesn't work at all (example from docs):
```ts
import { Bot, InlineQueryResult, InputMessageContent } from "gramio";
import { env } from "./env";

const bot = new Bot(env.BOT_TOKEN);

bot.inlineQuery(/find (.*)/i, async (context) => {
	if (context.args) {
		await context.answer([
			InlineQueryResult.article(
				"id-1",
				`Result for ${context.args.at(1)}`,
				InputMessageContent.text(`This is a message result for ${context.args.at(1)} query`)
			),
		]);
	}
});

bot.start();
```

<img width="824" alt="image" src="https://github.com/user-attachments/assets/265d9c9a-4515-4ff7-9663-cc4304de9267">

edit: nevermind, you have to enable it, see these docs https://grammy.dev/plugins/inline-query

**Comment by kravetsone** [comment]
Oh i should add warning about it to the documentation as in [choseninlineresult](https://gramio.dev/triggers/chosen-inline-result#choseninlineresult)

Thanks!
